module.exports = {
    dev:[
        'react',
        'js',
        'javascript',
        'angular',
        'ecmascript',
        'swift',
        'aws',
        'devops',
        'container',
        'released',
        'firebase',
        'ionic',
        'cloud',
        'web',
        'app',
        'node',
        'nodejs'
    ],
    users:[
        'addyosmani',
        'googledevs',
        'Firebase',
        'nathankpeck',
        'javascriptd',
        'BenLesh',
        '_jayphelps',
        'ChromeDevTools',
        'awscloud'
    ]
}